In [ ]:
# Broadcasting or stretching
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 8, 9])
print(a + b)
print('---------------')
c = np.ones((2, 2))
print(c)
print('---------')
a + c # Error

## Explanation of above example


# Rules of broadcasting

1. If the arrays mismatched in dimensions then the array with fewer dimensions is padded on the left with the one.

2. After applying rule 1, if any of the dimensions of the 2 arrays doesnot match then the mismatching dimension is strecthed to match the other array's dimension. The stretching always happens w.r.t that array whose value of the dimension is 1.

3. After applying rule 2, if still there is a mismatch in the dimensions and error is raised

In [3]:
# Example 1
a = np.ones((2, 3))
b = np.arange(3)
print(a)
print('--------')
print(b)
print('--------')
print(a + b)

[[1. 1. 1.]
 [1. 1. 1.]]
--------
[0 1 2]
--------
[[1. 2. 3.]
 [1. 2. 3.]]


## Explanation of above example

a.shape ==> (2, 3)
b.shape ==> (3,)

- After applying rule 1
a.shape ==> (2, 3)
b.shape ==> (1, 3) ==> Pad one to the left of array

- After applying rule 2
a.shape ==> (2, 3)
b.shape ==> (2, 3) ==> stretch the array

In [4]:
# Example 2
a = np.ones((3, 1))
b = np.arange(3)
print(a)
print('--------')
print(b)
print('--------')
print(a.shape)
print(b.shape)
print('--------')
print(a + b)

[[1.]
 [1.]
 [1.]]
--------
[0 1 2]
--------
(3, 1)
(3,)
--------
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


## Explanation of above example
a.shape ==> (3, 1)
b.shape ==> (3, )

- After applying rule 1
a.shape ==> (3, 1)
b.shape ==> (1, 3)

- After applying rule 2
a.shape ==> (3, 1)
b.shape ==> (3, 3)
- Again rule 2 since one column is have value 1
a.shape ==> (3, 3)
b.shape ==> (3, 3)


In [5]:
# Example 3 
a = np.ones((3, 2))
b = np.arange(3)

a + b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

# Explanation of above example
a.shape ==> (3, 2)
b.shape ==> (3, )

- After applying rule 1
a.shape ==> (3, 2)
b.shape ==> (1, 3)

#### Array A

| 1st col | 2nd col |
| --- | --- |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |

#### Array B

|col 1 | col 2 | col 3|
| ----- | ----- | ---- |
| 1 | 2 | 3 |

- After applying rule 2
a.shape(3, 2)
b.shape(3, 3)

#### Array A
| 1st col | 2nd col |
| --- | --- |
| 1 | 1 |
| 1 | 1 |
| 1 | 1 |

#### Array B

| 1st col | 2nd col | 3rd col |
| --- | --- | ---- |
| 1 | 1 | 1 |
| 1 | 1 | 1 | 
| 1 | 1 | 1 |

- Still there is mismatch of dimensions error raises

In [12]:
"""
Adding a new dimension to the array
np.newaxis can be used to add a new dimension to an array when it is being indexed. 
Upon using newaxis once
    - 1 dim array becomes 2 dim
    - 2 dim array becomes 3 dim
    - 3 dim array bexcomes 4 dim and ...
"""
a = np.arange(3)
print(a)
print('--------')
b = a[:, np.newaxis]
print(b)
print('--------')
print(b.shape)

[0 1 2]
--------
[[0]
 [1]
 [2]]
--------
(3, 1)


In [11]:
b = np.ones((3, 3))
print(b)
b[:, np.newaxis, np.newaxis, :]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[[[1., 1., 1.]]],


       [[[1., 1., 1.]]],


       [[[1., 1., 1.]]]])