In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a[0:3]

array([1, 2, 3])

In [5]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(b[0:2, 1])
print(b[:, 1])
print(b[:, 1:3])
#print(b[0, 7]) # Error while accessing 1st element and last element
print(b[:, 0, 2])

[2 5]
[2 5 8]
[[2 3]
 [5 6]
 [8 9]]


IndexError: too many indices for array

In [19]:
flat_array = b.flatten()
print(flat_array)

[1 2 3 4 5 6 7 8 9]


In [20]:
for cell in b.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [26]:
#Arange function
arange_list = np.arange(10)
print(arange_list)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
arange_list_copy = arange_list[::2]
print(arange_list_copy)

[0 2 4 6 8]


In [28]:
np.shares_memory(arange_list, arange_list_copy)

True

In [30]:
arange_list_copy[2] = 32
print(arange_list_copy, arange_list)

[ 0  2 32  6  8] [ 0  1  2  3 32  5  6  7  8  9]


In [39]:
# copy function
a = np.arange(10)
b = a[::2].copy()
print(a, b)
b[0] = 20
print(a, b)
print(np.shares_memory(a,b))
# There is no deepcopy function

[0 1 2 3 4 5 6 7 8 9] [0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9] [20  2  4  6  8]
False


In [44]:
#Reshape function should fit the elements for an array
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#Reshape function
The above technique can be used to populate a matrix[2d-array] with a range of values.

In [48]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [47]:
b = a > 4
print(b)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [64]:
# Fancy indexing
a = np.arange(10)
print("Main array: {}".format(a))
mask = (a % 2 == 0)
print("mask: {}".format(mask))
b = a[mask]
print("masked array: {}".format(b))
print("Is sharing memory: {}".format(np.shares_memory(a, b)))
a[mask] = 23
print("Modified masked array: {}".format(a))

Main array: [0 1 2 3 4 5 6 7 8 9]
mask: [ True False  True False  True False  True False  True False]
masked array: [0 2 4 6 8]
Is sharing memory: False
Modified masked array: [23  1 23  3 23  5 23  7 23  9]


In [68]:
# Integer array indexing
a = np.arange(10)
print("Main array: {}".format(a))
print("Accessing some parts of array: {}".format(a[[2, 3, 9]]))
a[[2, 7]] = 32
print("Modified accessing array: {}".format(a))

Main array: [0 1 2 3 4 5 6 7 8 9]
Accessing some parts of array: [2 3 9]
Modified accessing array: [ 0  1 32  3  4  5  6 32  8  9]


A numpy array not only be accessed using slicing, it can also be accessed using boolean and integer arrays. This is also called fancy indexing. The result of fancy indexing is always a "copy" not a view.

In [75]:
#Scalar Operations on numpy array
a = np.arange(10)
b = a + 1
print("Original array: {}".format(a))
print("Modified array: {}".format(b))
print("Is sharing memory: {}".format(np.shares_memory(a, b)))
c = a ** 2
print("Another modified array: {}".format(c))

Original array: [0 1 2 3 4 5 6 7 8 9]
Modified array: [ 1  2  3  4  5  6  7  8  9 10]
Is sharing memory: False
Another modified array: [ 0  1  4  9 16 25 36 49 64 81]


In [77]:
# ELement wise operation of arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("Array a: {}".format(a))
print("Array b: {}".format(b))
c = a - b
print("Array subtraction c: {}".format(c))
print("Is c sharing memory with a: {}".format(np.shares_memory(a, c)))
print("Is c sharing memory with b: {}".format(np.shares_memory(b, c)))

Array a: [1 2 3 4]
Array b: [5 6 7 8]
Array c: [-4 -4 -4 -4]
Is c sharing memory with a: False
Is c sharing memory with b: False


In [83]:
a = np.arange(9).reshape(3, 3)
c = a * a
print("Element - Element multiplication: {}".format(c))

Element - Element multiplication: [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [82]:
b = a.dot(a)
print("Original Matrix multiplication: {}".format(b))

Original Matrix multiplication: [[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [86]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 4, 5, 4])
print(a > b)
print(a == b)

[False False False False]
[False False False  True]


In [87]:
a = np.arange(9).reshape(3, 3)
b = np.arange(6).reshape(3, 2)
print(a > b)

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [88]:
# Array wise comparision
a = np.arange(9).reshape(3, 3)
b = np.arange(6).reshape(3, 2)
print(np.array_equal(a, b))

False


In [90]:
a = np.array([2, 4, 5, 4])
b = np.array([2, 4, 5, 4])
print(np.array_equal(a, b))

True


In [91]:
np.array([1, 2, 3, 4]).reshape(2, 2)

array([[1, 2],
       [3, 4]])